name: WeeCheer
favicon: null
layout_spectrum: 0.63891
typography_spectrum: 0.47246
title: Wee Cheer - Developmental Cheer & Youth Dance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d70c8c'
    - '#f58152'
    - '#64cdd1'
    - '#f8b79c'
  brandStrength: 0.1875
  lightness: 0.8762572931591421
  saturation: 0.9538076864555478
  rhythmicContrast: 0.18991441559046507
purpose: []
